apiVersion: batch/v1                  
kind: Job                             
metadata:
  name: batch-job
spec:
  completions: 4
  parallelism: 2                                
  template:
    metadata:
      labels:                         
        app: batch-job                
    spec:
      restartPolicy: OnFailure        
      containers:
      - name: main
        image: localhost:5000/long-task:1.0