apiVersion: v1
kind: ReplicationController        
metadata:
  name: kubia                      
spec:
  replicas: 3                      
  selector:                        
    app: kubia                     
  template:                        
    metadata:                      
        labels:                      
          app: kubia                 
    spec:                          
      containers:                  
      - name: kubia                
        image: localhost:5000/node-app:1.3          
        ports:                     
        - containerPort: 8080      