apiVersion: v1
kind: Pod
metadata:
  name: kubia-liveness
spec:
  containers:
  - image: localhost:5000/node-app:1.3   
    name: kubia
    livenessProbe:                     
      httpGet:                         
        path: /                        
        port: 8080  